### ISSUE TITLE
Unable to use static export

### ISSUE THREAD

**Issue by fchengpc** [prismicio/prismic-nextjs-sample#2]
![screen shot 2018-09-07 at 4 00 22 pm](https://user-images.githubusercontent.com/6640631/45240621-49b29600-b2b7-11e8-99b0-45f3c4cad764.png)
one of the library is not playing nice. help?

**Comment by arnaudlewis** [comment]
You shouldn't face any issue with the static export anymore @fchengpc.
I updated the project yesterday for this purpose.
