### ISSUE TITLE
Preview cookie's maxAge incorrectly set

### ISSUE THREAD

**Issue by gleuch** [prismicio/prismic-nextjs-sample#3]
### Issue
The value set for `PREVIEW_EXPIRES` in [pages/preview.js](https://github.com/prismicio/prismic-nextjs-sample/blob/703b2a4a09996fcea5e1bbe8b0eb2febb9c6bda2/pages/preview.js#L6) attempts to set an expiration in milliseconds.

Per [`cookie`'s](https://www.npmjs.com/package/cookie#maxage) documentation, `maxAge` accepts a value in seconds, not milliseconds. The current example has the cookie expiring after 20.83 days, not 30 minutes.

Developers using this code will run into request issues since the preview URLs/session will have expired long before the preview cookie expires.

### Solution
Change `PREVIEW_EXPIRES` on [line 6 of pages/preview.js](https://github.com/prismicio/prismic-nextjs-sample/blob/703b2a4a09996fcea5e1bbe8b0eb2febb9c6bda2/pages/preview.js#L6) to reflect a value in seconds, not milliseconds, e.g. 30 minutes.
```
const PREVIEW_EXPIRES = 1800;
```

### Sidenote
Other cookie packages/implementations may require `maxAge` in milliseconds.

**Comment by arnaudlewis** [comment]
Thanks for your feedback @gleuch, the preview is now handled entirely by Prismic.js so It shouldn't be an issue anymore.
