### ISSUE TITLE
Preview script and iframe always loaded

### ISSUE THREAD

**Issue by skinread** [prismicio/prismic-nextjs-sample#7]
One thing that I have noticed with this approach is that the `<script src="//static.cdn.prismic.io/prismic.min.js" />` is not conditionally loaded for the preview mode so all users are forced to download this library as well as jQuery.

If there are any ideas for checking headers, etc, for preview mode and only injecting the script when needed it would be help keep the page as small as possible.

**Comment by arnaudlewis** [comment]
Hi @skinread, the Prismic script is not meant only for preview. It's useful for preview/shareable previews/A/B testing/edit button and multiple future features so it should be there at all time.

**Comment by skinread** [comment]
Hi @arnaudlewis thanks for clarifying. Is there somewhere I can raise my general concern for the way the script/iframe are loaded for all users even if the functionality will never be used?
I'm seeing them decrease Lighthouse scores so it would be great to understand the background and Prismic's thoughts on performance. Cheers

**Comment by arnaudlewis** [comment]
Don't worry , it offers useful feature for logged in users but any of the
visitors will be impacted, it won't load the iframe and run the js.
